name: Price Checker

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  check_price:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up SQLite Database
        run: |
          python -c "import sqlite3; conn = sqlite3.connect('config.db'); cursor = conn.cursor(); cursor.execute(\"CREATE TABLE IF NOT EXISTS tracking (product_url TEXT PRIMARY KEY, min_price INTEGER, max_price INTEGER, sku TEXT)\"); conn.commit(); conn.close();"

      - name: Run Price Checker
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python price_checker.py
